### PR TITLE
i18n: translation to Ukrainian

### PR DESCRIPTION
**Pull request by pixelspark**

### CODE REVIEW

**Review by 1kalina — APPROVED** [review]
I'm so sorry for the late review.
I checked all the translations, and they look good

**Review by 1kalina — CHANGES_REQUESTED** [review]
I'm so sorry for the late review.
I checked all the translations, and they look good.
However, not UK — UA is correct. UK is specifically for the United Kingdom.

**Comment by pixelspark** [comment]
Thanks! This has been merged now. Strangely it seems 'uk' is actually the language code used by Apple/XCode to indicate Ukrainian:

image

Please go over the master version of the localized file once again, many new strings have been added. If you see anything weird there, let me know!

https://github.com/pixelspark/sushitrain/commit/34ff1f220e857a02e04f9581ee8ad679cf5b672b

**Comment by 1kalina** [comment]
Strange. But actually translation looks good. Thank you

**Pull request merged**
